apiVersion: apps/v1
kind: Deployment
metadata:
  name: chirpstack-webhook
spec:
  template:
    metadata:
      annotations:
        vault.hashicorp.com/agent-inject-secret-credentials.txt: "secret/data/chirpstack-webook-creds"
        vault.hashicorp.com/agent-inject-template-credentials: |
          {{ with secret "secret/data/chirpstack-webook-creds" }}
          export DATABASE_URL="{{ .Data.data.database_url }}"
          {{ end }}
    spec:
      containers:
        - name: chirpstack-webhook
