apiVersion: v1
kind: Service
metadata:
  name: chirpstack-webhook
spec:
  selector:
    app: chirpstack-webhook
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 3006
  type: ClusterIP
