apiVersion: v1
kind: Service
metadata:
  name: timescale-bridge
spec:
  selector:
    app: timescale-bridge
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 3006
  type: ClusterIP
